name: Advent Of Code

on:
  push:
    branches: [ main ]
    paths:
    - '**/AdventOfCode/**'
    - '.github/workflows/AdventOfCode.yml'

env:
  BASE_URL: https://adventofcode.com
  SESSION_ID: ${{ secrets.ADVENTOFCODE_SESSION_ID }}
  DAY: 5

defaults:
  run:
    working-directory: ./AdventOfCode/2020

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.run.outputs.result }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Install dependencies
      run: |
        cabal update
        cabal build AdventOfCode2020:Day${DAY} --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run:  cabal build AdventOfCode2020:Day${DAY} --enable-tests --enable-benchmarks
    - name: Download input file
      run: curl -b "session=${SESSION_ID}" ${BASE_URL}/2020/day/${DAY}/input > input
    - name: Run
      run: cabal run AdventOfCode2020:Day${DAY} < input
