name: Advent Of Code

on:
  push:
    branches: [ main ]
    paths:
    - '**/AdventOfCode/**'
    - '.github/workflows/adventofcode.yml'

env:
  BASE_URL: https://adventofcode.com
  SESSION_ID: ${{ secrets.ADVENTOFCODE_SESSION_ID }}
  DAY: 1

defaults:
  run:
    working-directory: ./AdventOfCode/2020

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.run.outputs.result }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Day
      run : echo 'Day number is ${Day}'
    - name: Build
      run:  ghc Day${DAY}.hs
    - name: Download input file
      run: curl -b "session=${SESSION_ID}" ${BASE_URL}/2020/day/${DAY}/input > input
    - name: Run
      id: run
      run: |
        ./Day${DAY} < input > output
        output=$(cat output); echo '::set-output name=result::'$output
