name: Advent Of Code

on:
  push:
    branches: [ main ]
    paths:
    - '**/AdventOfCode/**'
    - '.github/workflows/AdventOfCode.yml'

env:
  BASE_URL: https://adventofcode.com
  SESSION_ID: ${{ secrets.ADVENTOFCODE_SESSION_ID }}
  YEAR: 2020
  DAY: 14

defaults:
  run:
    working-directory: ./AdventOfCode/2020

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.run.outputs.result }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Cache
      id: cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal build AdventOfCode${YEAR}:Day${DAY} --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run:  cabal build AdventOfCode${YEAR}:Day${DAY} --enable-tests --enable-benchmarks

    - name: Get puzzle input
      run: |
        STATUS=$(curl -b "session=${SESSION_ID}" \
          ${BASE_URL}/${YEAR}/day/${DAY}/input -O \
          -w '%{http_code}' -s)
        if [ $STATUS -eq 400 ]; then
          echo 'Token has been expired'
          return 1
        fi

    - name: Run
      id: run
      run: |
        output=$(cabal --verbose=0 run AdventOfCode${YEAR}:Day${DAY} < input)
        echo '::set-output name=result::'$output

    - name: Get the part
      id: check
      run: |
        ONE_STAR_PATTERN="Day ${DAY}, one star"
        TWO_STARS_PATTERN="Day ${DAY}, two stars"

        curl -# -b "session=${SESSION_ID}" ${BASE_URL}/${YEAR} -o main

        if cat main | grep -q -E "$TWO_STARS_PATTERN"; then
          echo 'Both parts of the puzzle are complete! They provide two gold stars: **'
          echo '::set-output name=resubmition::true'
        elif cat main | grep -q -E "$ONE_STAR_PATTERN"; then
          echo '::set-output name=resubmition::false'
          echo '::set-output name=part::2'
        else
          echo '::set-output name=resubmition::false'
          echo '::set-output name=part::1'
        fi

    - name: Submit
      if: steps.check.outputs.resubmition != 'true'
      run: |
        PART="${{ steps.check.outputs.part }}"
        ANSWER="${{ steps.run.outputs.result }}"
        curl -# -X POST -d "level=$PART&answer=$ANSWER" \
          ${BASE_URL}/${YEAR}/day/${DAY}/answer \
          --raw -b "session=${SESSION_ID}" -o result
        cat result | grep '<article>'
        cat result | grep -q -E "That's the right answer!"

    - name: Update Readme
      if: steps.check.outputs.resubmition != 'true'
      run: |
        PART="${{ steps.check.outputs.part }}"
        if [ $PART = "1" ]; then
          answer="${{ steps.run.outputs.result }}"
          search="(Day ${DAY}).*$"
          replace="\| \1 \| $answer \| \| ⭐ \|"
        elif [ $PART = "2" ]; then
          answer="${{ steps.run.outputs.result }}"
          search="(\| Day ${DAY} \| .*) \| \| ⭐ \|"
          replace="\1 \| $answer \| ⭐⭐ \|"
        else
          echo "Unknown part: '$PART'"
          return 1
        fi
        script="s/$search/$replace/1"
        sed --in-place -r -e "$script" README.md
      working-directory: .

    - name: Commit Readme
      if: steps.check.outputs.resubmition != 'true'
      run: |
        PART="${{ steps.check.outputs.part }}"
        if [ $PART = "1" ]; then
          MESSAGE="[CI Bot]: Obtain the first star for 'Day ${DAY}'"
        elif [ $PART = "2" ]; then
          MESSAGE="[CI Bot]: Obtain the second star for 'Day ${DAY}'"
        else
          echo "Unknown part: '$PART'"
          return 1
        fi
        git config user.name 'CI Bot'
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "$MESSAGE"
        git push
      working-directory: .

    - name: Debug failure
      if: ${{ failure() }}
      run: |
        echo 'cat input'
        cat input
        echo 'cat main'
        cat main
        echo 'cat result'
        cat result
