name: Advent Of Code

on:
  push:
    branches: [ main ]
    paths:
    - '**/AdventOfCode/**'
    - '.github/workflows/adventofcode.yml'

env:
  BASE_URL: https://adventofcode.com
  SESSION_ID: ${{ secrets.ADVENTOFCODE_SESSION_ID }}

defaults:
  run:
    working-directory: ./AdventOfCode/2020

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Build 'Day 1 - Report Repair'
      run:  ghc Day1.hs
    - name: Download input file for 'Day 1'
      run: curl -b "session=${SESSION_ID}" ${BASE_URL}/2020/day/1/input > input1
    - name: Run 'Day 1 - Report Repair'
      run: ./Day1 < ./input1
