name: Advent Of Code

on:
  push:
    branches: [ main ]
    paths:
    - '**/AdventOfCode/**'
    - '.github/workflows/AdventOfCode.yml'

env:
  BASE_URL: https://adventofcode.com
  SESSION_ID: ${{ secrets.ADVENTOFCODE_SESSION_ID }}
  YEAR: 2020
  DAY: 7
  PART: 2

defaults:
  run:
    working-directory: ./AdventOfCode/2020

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.run.outputs.result }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Cache
      id: cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cabal update
        cabal build AdventOfCode${YEAR}:Day${DAY} --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run:  cabal build AdventOfCode${YEAR}:Day${DAY} --enable-tests --enable-benchmarks
    - name: Download input file
      run: curl -# -b "session=${SESSION_ID}" ${BASE_URL}/${YEAR}/day/${DAY}/input > input
    - name: Run
      id: run
      run: |
        output=$(cabal --verbose=0 run AdventOfCode${YEAR}:Day${DAY} < input)
        echo '::set-output name=result::'$output
    - name: Post the answer
      run: |
        curl -# -X POST -d "level=${PART}&answer=${{ steps.run.outputs.result }}" --raw -b "session=${SESSION_ID}" ${BASE_URL}/${YEAR}/day/${DAY}/answer > result
        cat result | grep '<article>'
        cat result | grep -q -E "That's the right answer!|Did you already complete it?"
