name: Pentamino

on:
  push:
    branches: [ main ]
    paths:
    - '**/Pentamino/**'
    - '.github/workflows/Pentamino.yml'

defaults:
  run:
    working-directory: ./Pentamino

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        puzzle: ["(3, 20)", "(4, 15)", "(5, 12)", "(6, 10)", "(10, 6)", "(12, 5)", "(15, 4)", "(20, 3)"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.2'
        cabal-version: '3.4'

    - name: Run
      run:  cabal run Pentamino:Pentamino
      with:
        PENTAMINO_SIZE = ${{ matrix.puzzle }}


